name: ci for agentic form filler
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [ '3.10', '3.11' ]
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.pyver }}
            architecture: 'x64'
        - run: |
            flake8 agentic_document_form_filler --count --show-source --statistics
            python -m pip install --upgrade pip
            pip install -e .